insert into event (event_nm, date_st, date_end) values ('Miami Valley Rgional', 2018-02-28, 2018-03-03);

insert into team (team_no, event_id, team_nm) values ('48', 1, 'Delphi E.L.I.T.E.');
insert into team (team_no, event_id, team_nm) values ('63', 1, 'McDowell Robotics Team 63');
insert into team (team_no, event_id, team_nm) values ('128', 1, 'The Bobcats');
insert into team (team_no, event_id, team_nm) values ('144', 1, 'The R.O.C.K.');
insert into team (team_no, event_id, team_nm) values ('234', 1, 'Cyber Blue');
insert into team (team_no, event_id, team_nm) values ('247', 1, 'Da Bears');
insert into team (team_no, event_id, team_nm) values ('279', 1, 'Tech Fusion');
insert into team (team_no, event_id, team_nm) values ('291', 1, 'CIA - Creativity In Action');
insert into team (team_no, event_id, team_nm) values ('304', 1, 'The Bobcats');
insert into team (team_no, event_id, team_nm) values ('337', 1, 'Hard Working Hard Hats');
insert into team (team_no, event_id, team_nm) values ('379', 1, 'RoboCats');
insert into team (team_no, event_id, team_nm) values ('451', 1, 'The Cat Attack');
insert into team (team_no, event_id, team_nm) values ('554', 1, 'The Bluegrease Crew');
insert into team (team_no, event_id, team_nm) values ('677', 1, 'Murphy''s Outlaw');
insert into team (team_no, event_id, team_nm) values ('1014', 1, 'Bad Robots');
insert into team (team_no, event_id, team_nm) values ('1038', 1, 'Lakota Robotics');
insert into team (team_no, event_id, team_nm) values ('1317', 1, 'Digital Fusion');
insert into team (team_no, event_id, team_nm) values ('1466', 1, 'Webb Robotics');
insert into team (team_no, event_id, team_nm) values ('1559', 1, 'Devil Tech');
insert into team (team_no, event_id, team_nm) values ('1675', 1, 'UPS (Ultimate Protection Squad)');
insert into team (team_no, event_id, team_nm) values ('2172', 1, 'Street Legal');
insert into team (team_no, event_id, team_nm) values ('2252', 1, 'The Mavericks');
insert into team (team_no, event_id, team_nm) values ('2399', 1, 'The Fighting Unicorns');
insert into team (team_no, event_id, team_nm) values ('2603', 1, 'Steel Stingers');
insert into team (team_no, event_id, team_nm) values ('3010', 1, 'The Red Plague');
insert into team (team_no, event_id, team_nm) values ('3138', 1, 'Innovators Robotics');
insert into team (team_no, event_id, team_nm) values ('3193', 1, 'Falco Tech');
insert into team (team_no, event_id, team_nm) values ('3201', 1, 'Ross Rambotics');
insert into team (team_no, event_id, team_nm) values ('3260', 1, 'SHARP');
insert into team (team_no, event_id, team_nm) values ('3266', 1, 'Robots-R-Us');
insert into team (team_no, event_id, team_nm) values ('3324', 1, 'The Metrobots');
insert into team (team_no, event_id, team_nm) values ('3397', 1, 'Robolions');
insert into team (team_no, event_id, team_nm) values ('3484', 1, 'Short Circuit');
insert into team (team_no, event_id, team_nm) values ('3492', 1, 'P.A.R.T.s');
insert into team (team_no, event_id, team_nm) values ('3504', 1, 'Girls of Steel');
insert into team (team_no, event_id, team_nm) values ('3777', 1, 'Bean  City Bots');
insert into team (team_no, event_id, team_nm) values ('3844', 1, 'Kentucky Wildbots');
insert into team (team_no, event_id, team_nm) values ('3940', 1, 'CyberTooth');
insert into team (team_no, event_id, team_nm) values ('4028', 1, 'The Beak Squad');
insert into team (team_no, event_id, team_nm) values ('4085', 1, 'Technical Difficulties');
insert into team (team_no, event_id, team_nm) values ('4121', 1, 'Vikings');
insert into team (team_no, event_id, team_nm) values ('4145', 1, 'WorBots');
insert into team (team_no, event_id, team_nm) values ('4283', 1, 'INSPIRE Robotics');
insert into team (team_no, event_id, team_nm) values ('4284', 1, 'ScotBot4284');
insert into team (team_no, event_id, team_nm) values ('4362', 1, 'Gems');
insert into team (team_no, event_id, team_nm) values ('4467', 1, 'Titanium Titans');
insert into team (team_no, event_id, team_nm) values ('4521', 1, 'Harrison Robotics');
insert into team (team_no, event_id, team_nm) values ('4611', 1, 'O-Zone');
insert into team (team_no, event_id, team_nm) values ('5413', 1, 'Stellar Robotics');
insert into team (team_no, event_id, team_nm) values ('5418', 1, 'The Sonic Screwdrivers');
insert into team (team_no, event_id, team_nm) values ('5492', 1, 'Winner''s Circle Robo Jockeys');
insert into team (team_no, event_id, team_nm) values ('5667', 1, 'The Digital Eagles');
insert into team (team_no, event_id, team_nm) values ('5740', 1, 'CWNC-Trojanators');
insert into team (team_no, event_id, team_nm) values ('5811', 1, 'BONDS');
insert into team (team_no, event_id, team_nm) values ('6032', 1, 'Pirate Robotics');
insert into team (team_no, event_id, team_nm) values ('6084', 1, 'Swoop Robotics');
insert into team (team_no, event_id, team_nm) values ('6460', 1, 'Air Guardians');
insert into team (team_no, event_id, team_nm) values ('6765', 1, 'Columbus City Schools Walnut Ridge Scotts');
insert into team (team_no, event_id, team_nm) values ('6834', 1, 'Bionic Warriors');
insert into team (team_no, event_id, team_nm) values ('6927', 1, 'The Franklinton Firebirds');
insert into team (team_no, event_id, team_nm) values ('6936', 1, 'The Beaver Bots - Vault 6936');
insert into team (team_no, event_id, team_nm) values ('7165', 1, 'Perkins Pirates');